### ISSUE TITLE
where is the hardware ?

### ISSUE THREAD

**Issue by PierreKircher** [chaibio/chaipcr#15]
refereing to your kickstarter promisse 

The hardware design, including BOM, SolidWorks files, and Eagle CAD will all be released as open source when the machine ships, and are available sooner as an early access reward.

the mashine certainly shipped already, but there is no sign of the hardware anywhere ?

**Comment by jperfetto** [comment]
The hardware was released on GrabCAD: https://grabcad.com/library/chai-open-qpcr-1

**Comment by PierreKircher** [comment]
thank you very much - it might be helpfull to have this in the repo readme !
